// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mfzjyNP9ORUbV0tvZC5IeCUXcXCyuzo',
    appId: '1:274476647081:web:b104448a8b2b8065199fb8',
    messagingSenderId: '274476647081',
    projectId: 'dahy-company',
    authDomain: 'dahy-company.firebaseapp.com',
    storageBucket: 'dahy-company.firebasestorage.app',
    measurementId: 'G-ZY7TGMKYKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlDPcgqkd0ypvSdDBeXJKOxQW3NJG4DQ',
    appId: '1:274476647081:android:9a0aa66440dc970e199fb8',
    messagingSenderId: '274476647081',
    projectId: 'dahy-company',
    storageBucket: 'dahy-company.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtilK44-1kjZ6xw1GVyG5mXeLp-CWlVyI',
    appId: '1:274476647081:ios:9527a0b2f0eb7107199fb8',
    messagingSenderId: '274476647081',
    projectId: 'dahy-company',
    storageBucket: 'dahy-company.firebasestorage.app',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtilK44-1kjZ6xw1GVyG5mXeLp-CWlVyI',
    appId: '1:274476647081:ios:9527a0b2f0eb7107199fb8',
    messagingSenderId: '274476647081',
    projectId: 'dahy-company',
    storageBucket: 'dahy-company.firebasestorage.app',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2mfzjyNP9ORUbV0tvZC5IeCUXcXCyuzo',
    appId: '1:274476647081:web:3c2921768fd24496199fb8',
    messagingSenderId: '274476647081',
    projectId: 'dahy-company',
    authDomain: 'dahy-company.firebaseapp.com',
    storageBucket: 'dahy-company.firebasestorage.app',
    measurementId: 'G-JPV2G1HB9P',
  );
}
